name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with report
        run: pytest --junitxml=./report/report.xml
      - name: Upload test report on failure
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./report/report.xml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()
    steps:
       - uses: actions/checkout@v3
       - name: Deploy application
         run: bash ./deploy.sh production

  notify:
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download test report artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./report
          
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # Paramètres du serveur Gmail
          server_address: smtp.gmail.com
          server_port: 465 # Port sécurisé SSL
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          
          # Contenu de l'email
          subject: " ${{ job.status }} du workflow : ${{ github.repository }}"
          to: chokri.gammoudi@gmail.com
          from: "GitHub Actions <${{ secrets.GMAIL_USERNAME }}>"
          body: | 
                the Job done with ${{ job.status }} for the commit ${{ github.sha }} .
                for more details please check the atached report
          # Optionnel : Pièce jointe
          attachments: ./report/report.xml


